# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml

WARP_ENABLE_WAYLAND = 1


[wallpaper]
custom_paths = [
    "$HOME/Pictures/Wallpapers",
] # List of paths to search for wallpapers

[wallpaper.swww]
framerate = 60 # transition framerate
duration = 1   # transition duration
# Transition type [ none | simple | fade | left | right | top | bottom | wipe | wave | grow | center | any | outer | random ]
transition_next = "grow"    # transition type for next wallpaper
transition_prev = "outer"   # transition type for previous wallpaper
transition_default = "grow" # transition type for default wallpaper


[rofi]
scale = 10 # rofi default scaling

[rofi.hyprlock]
scale = 10

[rofi.animation]
scale = 8

[rofi.glyph]
scale = 8

[rofi.launcher]
# style = "10"
scale = 5

[rofi.cliphist]
scale = 8

[rofi.wallpaper]
scale = 8

[rofi.emoji]
style = 2
scale = 8

[rofi.theme]
scale = 6

[wlogout]
style = 2

[battery.notify]
timer = 120
notify = 1140
interval = 5
dock = true

[battery.notify.threshold]
full = 90
critical = 10
low = 20
unplug = 80


[battery.notify.execute]
unplug = ""
low = ""
critical = "systemctl suspend"
charging = ""
discharging = ""

[keybind.hint]

[rofi.keybind.hint]
delimiter = "\t"
width = "40em"
height = "40em"
line = 16

[screenshot]
annotation_tool = "swappy" # Annotation tool
annotation_pre_command = [
    # 'shader=$(hyprshade current) && hyprshade off && trap restore_shader EXIT', # Use this when you're using hyprshade
] # Pre command for annotation tool
annotation_post_command = [
    # "[ -n \"\\$shader\" ] && hyprshade on \\$shader", # Use this when you're using hyprshade
    "",
] # Post command for annotation tool


[rofi.bookmark]
file = "$HOME/.config/hyde/bookmarks.lst"

[rofi.search]
file = "$HOME/.config/hyde/search.lst"


[wallbash]
skip_template = [
    "",
] # skips the template when using wallbash. Requires full path to the template

[waybar]
font = "JetBrainsMono Nerd Font"
font_size = 10
# output = ["", ""]                # Default monitor output for waybar


[cava.stdout]
# 'cava.sh stdout' configuration
max_instances = 1 # Maximum number of cava instances // fix and workaround when a process won't kill 'cava ' process
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"
width = 20
range = 7         # Number of (bars -1)
standby = "ğŸ¶"

[cava.hyprlock]
# 'cava.sh hyprlock' configuration
max_instances = 1 # Maximum number of cava instances // fix and workaround when a process won't kill 'cava ' process
bar = "ğŸŒ‘ğŸŒ’ğŸŒ“ğŸŒ”ğŸŒ•ğŸŒ–ğŸŒ—ğŸŒ˜"
width = 20
range = 7
standby = "ğŸ¶"

[cava.waybar]
# 'cava.sh waybar' configuration
max_instances = 1 # Maximum number of cava instances // fix and workaround when waybar won't kill 'cava ' process
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"
width = 20
range = 7
standby = "ğŸ¶"


[hypr.config]
# List of regex to sanitize in the theme.config // Useful for deprecated options to be removed from the theme.config
sanitize = [
    '.*rgba\(.*,*,*,*,',
] # Remove all rgba colors // workarounds for rgba colors crashing hyprland

[volume]
notify = true # Useful for systems that have their own OSD
steps = 5     # Number of steps to increase/decrease volume

[brightness]
notify = true # Useful for systems that have their own OSD
steps = 5     # Number of steps to increase/decrease brightness
